### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by kim-lux** [lukovicaleksa/autonomous-driving-turtlebot-with-reinforcement-learning#3] opened 2021-07-07 11:06 UTC
I am interested in this video. And I just want to follow this . But I'm a beginner of ROS.
So I'cant begin this git project. When I run this project, gazebo simulation is fail (turtlebot is crashed)
I think this is because I just run each python file. (like use this command to run scan_node.py $ python scan_node.py)
Can you explain how can I run this whole file. (like rqt graph)
I think I must use roslaunch command but I don't know how can i use this command.

could you give me a code when you start this simulation in gazebo?

**Comment by lukovicaleksa** [comment] 2021-07-07 11:17
In order to run ROS nodes you need to use rosrun command, roslaunch is for
running the ROS packages like Gazebo Simulator.
I suggest you follow this tutorial on ROS Wiki if you want to learn the
basics of ROS:
http://wiki.ros.org/ROS/Tutorials
After you learn the basics of ROS architecture, only then you can start
building some projects.

**Comment by kim-lux** [comment] 2021-07-07 12:39
we already study basics of ROS architecture
and we run this project with this code
rosrun master_rad control_node.py
When we use 0, 2 path, we are success
but the other path we are failed
When you process this project , Did you success all the pass?
thank you for your response
l am honored to study this project

**Comment by lukovicaleksa** [comment] 2021-07-07 13:42
I cant really tell you from here what exactly the problem is. That node is
doing the basic feedback control, with no Q-learning included. Can you tell
me what the exact problem is?
Does robot spawns to the proper position?
Does robot reaches the goal position?
Note this: You cant expect the robot to avoid obstacles using this node, it
is only the pure feedback control without using the Lidar information, i
used it in the RViz blank world just to test the feedback control.

**Comment by lukovicaleksa** [comment] 2021-07-07 13:47
oh im sorry i-ve read it wrong, the feedback_control_node does what i just
said, the control_node includes the Q-learning and should avoid obstacles.
Yes, i succeeded in all paths ofcourse. So can you tell me what is the
exact problem for you?
The robot is not avoiding obstacles properly?

**Comment by kim-lux** [comment] 2021-07-14 10:52
Sorry for the late reply. We run control_node.py via rosrun but everything fails except path 0,2 as pictured. I'm not sure why this is wrong. is there another important code for run this program? we just use rosrun master_rad control_node.py. Please let us know if we are doing anything wrong. thanks for the reply
![path4](https://user-images.githubusercontent.com/69554273/125610343-9f1bfadd-ceff-453e-8bf9-2d84958cde77.jpg)
![path1](https://user-images.githubusercontent.com/69554273/125610351-3ec21565-c287-42c5-8f61-7f795290ca3f.jpg)

**Comment by lukovicaleksa** [comment] 2021-07-14 11:14
Yes, that's how you run the code, nothing else needs to be done. Just choose the path at the top of the .py file and it should work. Which version of ROS and Linux are you using? By the look of your screen i guess you are using newer version of Linux and and ROS probobly, i used Linux 16.04 and ROS Kinetic Kame on the virtual machine. Everything should work fine, the version of code posted here is the final version that worked for me.

**Comment by kim-lux** [comment] 2021-07-14 11:58
Thanks for your kind reply. I'll check it out and post back.

**Comment by kim-lux** [comment] 2021-07-16 02:53
I ran it with 16.04 kenetic and still got the same result. Having trouble running it in a VM? thanks for the response
![Path4](https://user-images.githubusercontent.com/69554273/125884512-99305f1e-d218-43db-a0d4-f8482ed9a9e3.png)

**Comment by lukovicaleksa** [comment] 2021-07-16 06:16
Then im afraid i dont know from here what the problem is, i will try to debug these days when i get time. Hope i will solve the problem and answer you as soon as possible.

**Comment by lukovicaleksa** [comment] 2021-07-16 18:20
Fixed everything, scripts had few bugs that i left while i was testing. I did one more learning phase and acquired new Q-table which is stored in Log_learning_FINAL folder. Everything works fine now. 
One note: beware of the feedback controller parameters and goal distance and angle threshold, reaching goal depends a lot on these. 
Please let me know if all paths work for you now, so i can close the issue.

**Comment by kim-lux** [comment] 2021-07-17 00:43
Thanks for your hard work. But unfortunately I can't seem to get Q-learning to work properly in this code. The terminal says Q-learniing is being applied, but there are many times when the direction change does not occur. Could you please let me know what the problem is? Now it crashes on all paths. Thank you always.

![image](https://user-images.githubusercontent.com/69554273/126020293-446bb241-4f28-4f50-807d-d5adc5536849.png)

**Comment by lukovicaleksa** [comment] 2021-07-17 06:04
I have migrated my PC fully to Linux in the meantime. Now I am using Ubuntu 20.04 with ROS noetic.
PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
Please try with these versions, and if it still does not works i really dont have any idea why. Are you sure u downloaded the latest code?

**Comment by kim-lux** [comment] 2021-07-21 06:55
Finally succeeded. All thanks to you. Thank you very much. It worked because I matched the version. Thank you very much.

**Closed as completed** 2021-07-21 06:55 UTC

**Comment by lukovicaleksa** [comment] 2021-07-21 07:19
Your welcome! Im glad it works now
